// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "./internal/core/models.js";

export function AutoSelectLowestLatency(): $CancellablePromise<core$0.LatencyResult> {
    return $Call.ByID(1766018366).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BuildInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2153119103).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(55232683);
}

export function CloseConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2951556907, connectionID);
}

export function DeleteNode(nodeID: string): $CancellablePromise<void> {
    return $Call.ByID(1080831774, nodeID);
}

export function DetectIPDirect(): $CancellablePromise<core$0.IPDetectResult> {
    return $Call.ByID(2579987290).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DetectIPProxy(): $CancellablePromise<core$0.IPDetectResult> {
    return $Call.ByID(3095933365).then(($result: any) => {
        return $$createType2($result);
    });
}

export function EnsureCoreBinaries(): $CancellablePromise<void> {
    return $Call.ByID(2644454621);
}

export function ExportShortLink(nodeID: string): $CancellablePromise<string> {
    return $Call.ByID(2556485087, nodeID);
}

export function GetConfig(): $CancellablePromise<core$0.AppConfig> {
    return $Call.ByID(1200034045).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConnections(): $CancellablePromise<core$0.ActiveConnection[]> {
    return $Call.ByID(1541859132).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetLogs(level: string, limit: number): $CancellablePromise<core$0.LogEntry[]> {
    return $Call.ByID(1743981476, level, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetState(): $CancellablePromise<core$0.RuntimeState> {
    return $Call.ByID(2490316256).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetUsageHistory(limit: number): $CancellablePromise<core$0.UsageDay[]> {
    return $Call.ByID(3645314582, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ImportShortLink(name: string, link: string): $CancellablePromise<core$0.NodeConfig> {
    return $Call.ByID(4069088750, name, link).then(($result: any) => {
        return $$createType11($result);
    });
}

export function OpenConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2392342484);
}

export function OpenRuntimeDir(): $CancellablePromise<string> {
    return $Call.ByID(1333260438);
}

export function ProbeAllNodes(): $CancellablePromise<core$0.LatencyResult[]> {
    return $Call.ByID(3983201005).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ProbeNode(nodeID: string): $CancellablePromise<core$0.LatencyResult> {
    return $Call.ByID(2426717665, nodeID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RestartProxy(req: core$0.StartRequest): $CancellablePromise<void> {
    return $Call.ByID(1240580212, req);
}

export function SaveConfig(cfg: core$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(3442292638, cfg);
}

export function SetActiveNode(nodeID: string): $CancellablePromise<void> {
    return $Call.ByID(1112636605, nodeID);
}

export function SortNodesByLatency(): $CancellablePromise<void> {
    return $Call.ByID(1730788671);
}

export function SortNodesByName(): $CancellablePromise<void> {
    return $Call.ByID(3041695020);
}

export function StartProxy(req: core$0.StartRequest): $CancellablePromise<void> {
    return $Call.ByID(2835838209, req);
}

export function StartReverseForwarder(): $CancellablePromise<void> {
    return $Call.ByID(2642317999);
}

export function StopProxy(): $CancellablePromise<void> {
    return $Call.ByID(3345047379);
}

export function StopReverseForwarder(): $CancellablePromise<void> {
    return $Call.ByID(2275417685);
}

export function SwitchNode(nodeID: string): $CancellablePromise<void> {
    return $Call.ByID(1881690177, nodeID);
}

/**
 * TunAcquirePrivileges validates and caches the macOS login password for TUN
 * operations. The password is stored in-memory only and never written to disk.
 */
export function TunAcquirePrivileges(password: string): $CancellablePromise<void> {
    return $Call.ByID(4221577784, password);
}

/**
 * TunDropPrivileges clears any cached admin credentials used for TUN operations.
 */
export function TunDropPrivileges(): $CancellablePromise<void> {
    return $Call.ByID(3464546521);
}

/**
 * TunHasPrivileges reports whether the app can perform privileged TUN operations
 * silently on the current platform (macOS uses in-app sudo password caching).
 */
export function TunHasPrivileges(): $CancellablePromise<boolean> {
    return $Call.ByID(3950116500);
}

export function UpsertNode(node: core$0.NodeConfig): $CancellablePromise<core$0.NodeConfig> {
    return $Call.ByID(2714662214, node).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ValidateYAML(content: string): $CancellablePromise<void> {
    return $Call.ByID(1358246116, content);
}

// Private type creation functions
const $$createType0 = core$0.LatencyResult.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = core$0.IPDetectResult.createFrom;
const $$createType3 = core$0.AppConfig.createFrom;
const $$createType4 = core$0.ActiveConnection.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = core$0.LogEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = core$0.RuntimeState.createFrom;
const $$createType9 = core$0.UsageDay.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = core$0.NodeConfig.createFrom;
const $$createType12 = $Create.Array($$createType0);
