// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as core$0 from "../../../../SUDOKU-ASCII/sudoku-desktop/internal/core/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "core:log": core$0.LogEntry;
            "core:state": core$0.RuntimeState;
        }
    }
}
