// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class ActiveConnection {
    "id": string;
    "network": string;
    "source": string;
    "destination": string;
    "direction": string;
    "lastSeen": time$0.Time;
    "hits": number;

    /** Creates a new ActiveConnection instance. */
    constructor($$source: Partial<ActiveConnection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("hits" in $$source)) {
            this["hits"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveConnection($$parsedSource as Partial<ActiveConnection>);
    }
}

export class AppConfig {
    "version": number;
    "activeNodeId": string;
    "nodes": NodeConfig[];
    "routing": RoutingSettings;
    "tun": TunSettings;
    "core": CoreSettings;
    "reverseClient": ReverseClientSettings;
    "reverseForward": ReverseForwarderSettings;
    "portForwards": PortForwardRule[];
    "ui": UISettings;
    "lastStartedNode": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("activeNodeId" in $$source)) {
            this["activeNodeId"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("routing" in $$source)) {
            this["routing"] = (new RoutingSettings());
        }
        if (!("tun" in $$source)) {
            this["tun"] = (new TunSettings());
        }
        if (!("core" in $$source)) {
            this["core"] = (new CoreSettings());
        }
        if (!("reverseClient" in $$source)) {
            this["reverseClient"] = (new ReverseClientSettings());
        }
        if (!("reverseForward" in $$source)) {
            this["reverseForward"] = (new ReverseForwarderSettings());
        }
        if (!("portForwards" in $$source)) {
            this["portForwards"] = [];
        }
        if (!("ui" in $$source)) {
            this["ui"] = (new UISettings());
        }
        if (!("lastStartedNode" in $$source)) {
            this["lastStartedNode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField2_0($$parsedSource["nodes"]);
        }
        if ("routing" in $$parsedSource) {
            $$parsedSource["routing"] = $$createField3_0($$parsedSource["routing"]);
        }
        if ("tun" in $$parsedSource) {
            $$parsedSource["tun"] = $$createField4_0($$parsedSource["tun"]);
        }
        if ("core" in $$parsedSource) {
            $$parsedSource["core"] = $$createField5_0($$parsedSource["core"]);
        }
        if ("reverseClient" in $$parsedSource) {
            $$parsedSource["reverseClient"] = $$createField6_0($$parsedSource["reverseClient"]);
        }
        if ("reverseForward" in $$parsedSource) {
            $$parsedSource["reverseForward"] = $$createField7_0($$parsedSource["reverseForward"]);
        }
        if ("portForwards" in $$parsedSource) {
            $$parsedSource["portForwards"] = $$createField8_0($$parsedSource["portForwards"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField9_0($$parsedSource["ui"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class BandwidthSample {
    "at": time$0.Time;
    "txBps": number;
    "rxBps": number;
    "directBps": number;
    "proxyBps": number;
    "totalTx": number;
    "totalRx": number;

    /** Creates a new BandwidthSample instance. */
    constructor($$source: Partial<BandwidthSample> = {}) {
        if (!("at" in $$source)) {
            this["at"] = null;
        }
        if (!("txBps" in $$source)) {
            this["txBps"] = 0;
        }
        if (!("rxBps" in $$source)) {
            this["rxBps"] = 0;
        }
        if (!("directBps" in $$source)) {
            this["directBps"] = 0;
        }
        if (!("proxyBps" in $$source)) {
            this["proxyBps"] = 0;
        }
        if (!("totalTx" in $$source)) {
            this["totalTx"] = 0;
        }
        if (!("totalRx" in $$source)) {
            this["totalRx"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BandwidthSample instance from a string or object.
     */
    static createFrom($$source: any = {}): BandwidthSample {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BandwidthSample($$parsedSource as Partial<BandwidthSample>);
    }
}

export class CoreSettings {
    "sudokuBinary": string;
    "hevBinary": string;
    "workingDir": string;
    "localPort": number;
    "allowLan": boolean;
    "logLevel": string;
    "autoStart": boolean;

    /** Creates a new CoreSettings instance. */
    constructor($$source: Partial<CoreSettings> = {}) {
        if (!("sudokuBinary" in $$source)) {
            this["sudokuBinary"] = "";
        }
        if (!("hevBinary" in $$source)) {
            this["hevBinary"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("allowLan" in $$source)) {
            this["allowLan"] = false;
        }
        if (!("logLevel" in $$source)) {
            this["logLevel"] = "";
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreSettings($$parsedSource as Partial<CoreSettings>);
    }
}

export class HTTPMaskSettings {
    "disable": boolean;
    "mode": string;
    "tls": boolean;
    "host": string;
    "pathRoot": string;
    "multiplex": string;

    /** Creates a new HTTPMaskSettings instance. */
    constructor($$source: Partial<HTTPMaskSettings> = {}) {
        if (!("disable" in $$source)) {
            this["disable"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("tls" in $$source)) {
            this["tls"] = false;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("pathRoot" in $$source)) {
            this["pathRoot"] = "";
        }
        if (!("multiplex" in $$source)) {
            this["multiplex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPMaskSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPMaskSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPMaskSettings($$parsedSource as Partial<HTTPMaskSettings>);
    }
}

export class IPDetectResult {
    "ip": string;
    "region": string;
    "country": string;
    "isp": string;
    "source": string;
    "usedProxy": boolean;
    "checkedAtUnix": number;
    "error": string;

    /** Creates a new IPDetectResult instance. */
    constructor($$source: Partial<IPDetectResult> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("isp" in $$source)) {
            this["isp"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("usedProxy" in $$source)) {
            this["usedProxy"] = false;
        }
        if (!("checkedAtUnix" in $$source)) {
            this["checkedAtUnix"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPDetectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPDetectResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPDetectResult($$parsedSource as Partial<IPDetectResult>);
    }
}

export class LANProxyInfo {
    "port": number;
    "ips": string[];
    "ready": boolean;

    /** Creates a new LANProxyInfo instance. */
    constructor($$source: Partial<LANProxyInfo> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("ips" in $$source)) {
            this["ips"] = [];
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LANProxyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LANProxyInfo {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ips" in $$parsedSource) {
            $$parsedSource["ips"] = $$createField1_0($$parsedSource["ips"]);
        }
        return new LANProxyInfo($$parsedSource as Partial<LANProxyInfo>);
    }
}

export class LatencyResult {
    "nodeId": string;
    "nodeName": string;
    "latencyMs": number;
    "connectOk": boolean;
    "statusCode": number;
    "checkedAtUnix": number;
    "error": string;

    /** Creates a new LatencyResult instance. */
    constructor($$source: Partial<LatencyResult> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("nodeName" in $$source)) {
            this["nodeName"] = "";
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("connectOk" in $$source)) {
            this["connectOk"] = false;
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("checkedAtUnix" in $$source)) {
            this["checkedAtUnix"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatencyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LatencyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatencyResult($$parsedSource as Partial<LatencyResult>);
    }
}

export class LogEntry {
    "id": string;
    "timestamp": time$0.Time;
    "level": string;
    "component": string;
    "message": string;
    "raw": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class NodeConfig {
    "id": string;
    "name": string;
    "serverAddress": string;
    "key": string;
    "aead": string;
    "ascii": string;
    "paddingMin": number;
    "paddingMax": number;
    "enablePureDownlink": boolean;
    "customTable": string;
    "customTables": string[];
    "httpMask": HTTPMaskSettings;
    "localPort": number;
    "enabled": boolean;

    /** Creates a new NodeConfig instance. */
    constructor($$source: Partial<NodeConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("serverAddress" in $$source)) {
            this["serverAddress"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("aead" in $$source)) {
            this["aead"] = "";
        }
        if (!("ascii" in $$source)) {
            this["ascii"] = "";
        }
        if (!("paddingMin" in $$source)) {
            this["paddingMin"] = 0;
        }
        if (!("paddingMax" in $$source)) {
            this["paddingMax"] = 0;
        }
        if (!("enablePureDownlink" in $$source)) {
            this["enablePureDownlink"] = false;
        }
        if (!("customTable" in $$source)) {
            this["customTable"] = "";
        }
        if (!("customTables" in $$source)) {
            this["customTables"] = [];
        }
        if (!("httpMask" in $$source)) {
            this["httpMask"] = (new HTTPMaskSettings());
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeConfig {
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customTables" in $$parsedSource) {
            $$parsedSource["customTables"] = $$createField10_0($$parsedSource["customTables"]);
        }
        if ("httpMask" in $$parsedSource) {
            $$parsedSource["httpMask"] = $$createField11_0($$parsedSource["httpMask"]);
        }
        return new NodeConfig($$parsedSource as Partial<NodeConfig>);
    }
}

export class PortForwardRule {
    "id": string;
    "name": string;
    "listen": string;
    "target": string;
    "enabled": boolean;

    /** Creates a new PortForwardRule instance. */
    constructor($$source: Partial<PortForwardRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("listen" in $$source)) {
            this["listen"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardRule instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForwardRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardRule($$parsedSource as Partial<PortForwardRule>);
    }
}

export class ReverseClientSettings {
    "clientId": string;
    "routes": ReverseRoute[];

    /** Creates a new ReverseClientSettings instance. */
    constructor($$source: Partial<ReverseClientSettings> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseClientSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReverseClientSettings {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField1_0($$parsedSource["routes"]);
        }
        return new ReverseClientSettings($$parsedSource as Partial<ReverseClientSettings>);
    }
}

export class ReverseForwarderSettings {
    "dialUrl": string;
    "listenAddr": string;
    "insecure": boolean;

    /** Creates a new ReverseForwarderSettings instance. */
    constructor($$source: Partial<ReverseForwarderSettings> = {}) {
        if (!("dialUrl" in $$source)) {
            this["dialUrl"] = "";
        }
        if (!("listenAddr" in $$source)) {
            this["listenAddr"] = "";
        }
        if (!("insecure" in $$source)) {
            this["insecure"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseForwarderSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReverseForwarderSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReverseForwarderSettings($$parsedSource as Partial<ReverseForwarderSettings>);
    }
}

export class ReverseRoute {
    "path": string;
    "target": string;
    "stripPrefix"?: boolean | null;
    "hostHeader": string;

    /** Creates a new ReverseRoute instance. */
    constructor($$source: Partial<ReverseRoute> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("hostHeader" in $$source)) {
            this["hostHeader"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseRoute instance from a string or object.
     */
    static createFrom($$source: any = {}): ReverseRoute {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReverseRoute($$parsedSource as Partial<ReverseRoute>);
    }
}

export class RoutingSettings {
    "proxyMode": string;
    "ruleUrls": string[];
    "customRulesEnabled": boolean;
    "customRules": string;

    /** Creates a new RoutingSettings instance. */
    constructor($$source: Partial<RoutingSettings> = {}) {
        if (!("proxyMode" in $$source)) {
            this["proxyMode"] = "";
        }
        if (!("ruleUrls" in $$source)) {
            this["ruleUrls"] = [];
        }
        if (!("customRulesEnabled" in $$source)) {
            this["customRulesEnabled"] = false;
        }
        if (!("customRules" in $$source)) {
            this["customRules"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoutingSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): RoutingSettings {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ruleUrls" in $$parsedSource) {
            $$parsedSource["ruleUrls"] = $$createField1_0($$parsedSource["ruleUrls"]);
        }
        return new RoutingSettings($$parsedSource as Partial<RoutingSettings>);
    }
}

export class RuntimeState {
    "running": boolean;
    "coreRunning": boolean;
    "tunRunning": boolean;
    "reverseRunning": boolean;
    "startedAtUnix": number;
    "activeNodeId": string;
    "activeNodeName": string;
    "lastError": string;
    "traffic": TrafficState;
    "latencies": LatencyResult[];
    "connections": ActiveConnection[];
    "recentLogs": LogEntry[];
    "needsAdmin": boolean;
    "routeSetupError": string;

    /** Creates a new RuntimeState instance. */
    constructor($$source: Partial<RuntimeState> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("coreRunning" in $$source)) {
            this["coreRunning"] = false;
        }
        if (!("tunRunning" in $$source)) {
            this["tunRunning"] = false;
        }
        if (!("reverseRunning" in $$source)) {
            this["reverseRunning"] = false;
        }
        if (!("startedAtUnix" in $$source)) {
            this["startedAtUnix"] = 0;
        }
        if (!("activeNodeId" in $$source)) {
            this["activeNodeId"] = "";
        }
        if (!("activeNodeName" in $$source)) {
            this["activeNodeName"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("traffic" in $$source)) {
            this["traffic"] = (new TrafficState());
        }
        if (!("latencies" in $$source)) {
            this["latencies"] = [];
        }
        if (!("connections" in $$source)) {
            this["connections"] = [];
        }
        if (!("recentLogs" in $$source)) {
            this["recentLogs"] = [];
        }
        if (!("needsAdmin" in $$source)) {
            this["needsAdmin"] = false;
        }
        if (!("routeSetupError" in $$source)) {
            this["routeSetupError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeState instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeState {
        const $$createField8_0 = $$createType14;
        const $$createField9_0 = $$createType16;
        const $$createField10_0 = $$createType18;
        const $$createField11_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("traffic" in $$parsedSource) {
            $$parsedSource["traffic"] = $$createField8_0($$parsedSource["traffic"]);
        }
        if ("latencies" in $$parsedSource) {
            $$parsedSource["latencies"] = $$createField9_0($$parsedSource["latencies"]);
        }
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField10_0($$parsedSource["connections"]);
        }
        if ("recentLogs" in $$parsedSource) {
            $$parsedSource["recentLogs"] = $$createField11_0($$parsedSource["recentLogs"]);
        }
        return new RuntimeState($$parsedSource as Partial<RuntimeState>);
    }
}

export class StartRequest {
    "withTun": boolean;

    /** Creates a new StartRequest instance. */
    constructor($$source: Partial<StartRequest> = {}) {
        if (!("withTun" in $$source)) {
            this["withTun"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartRequest($$parsedSource as Partial<StartRequest>);
    }
}

export class TrafficState {
    "totalTx": number;
    "totalRx": number;
    "estimatedDirectTx": number;
    "estimatedDirectRx": number;
    "estimatedProxyTx": number;
    "estimatedProxyRx": number;
    "directConnDecisions": number;
    "proxyConnDecisions": number;
    "recentBandwidth": BandwidthSample[];
    "interface": string;
    "interfaceFound": boolean;
    "lastSampleUnixMillis": number;

    /** Creates a new TrafficState instance. */
    constructor($$source: Partial<TrafficState> = {}) {
        if (!("totalTx" in $$source)) {
            this["totalTx"] = 0;
        }
        if (!("totalRx" in $$source)) {
            this["totalRx"] = 0;
        }
        if (!("estimatedDirectTx" in $$source)) {
            this["estimatedDirectTx"] = 0;
        }
        if (!("estimatedDirectRx" in $$source)) {
            this["estimatedDirectRx"] = 0;
        }
        if (!("estimatedProxyTx" in $$source)) {
            this["estimatedProxyTx"] = 0;
        }
        if (!("estimatedProxyRx" in $$source)) {
            this["estimatedProxyRx"] = 0;
        }
        if (!("directConnDecisions" in $$source)) {
            this["directConnDecisions"] = 0;
        }
        if (!("proxyConnDecisions" in $$source)) {
            this["proxyConnDecisions"] = 0;
        }
        if (!("recentBandwidth" in $$source)) {
            this["recentBandwidth"] = [];
        }
        if (!("interface" in $$source)) {
            this["interface"] = "";
        }
        if (!("interfaceFound" in $$source)) {
            this["interfaceFound"] = false;
        }
        if (!("lastSampleUnixMillis" in $$source)) {
            this["lastSampleUnixMillis"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrafficState instance from a string or object.
     */
    static createFrom($$source: any = {}): TrafficState {
        const $$createField8_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentBandwidth" in $$parsedSource) {
            $$parsedSource["recentBandwidth"] = $$createField8_0($$parsedSource["recentBandwidth"]);
        }
        return new TrafficState($$parsedSource as Partial<TrafficState>);
    }
}

export class TunSettings {
    "enabled": boolean;
    "interfaceName": string;
    "mtu": number;
    "ipv4": string;
    "ipv6": string;
    "blockQuic": boolean;
    "socksUdp": string;
    "socksMark": number;
    "routeTable": number;
    "logLevel": string;
    "mapDnsEnabled": boolean;
    "mapDnsAddress": string;
    "mapDnsPort": number;
    "mapDnsNetwork": string;
    "mapDnsNetmask": string;
    "taskStackSize": number;
    "tcpBufferSize": number;
    "maxSession": number;
    "connectTimeout": number;

    /** Creates a new TunSettings instance. */
    constructor($$source: Partial<TunSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("interfaceName" in $$source)) {
            this["interfaceName"] = "";
        }
        if (!("mtu" in $$source)) {
            this["mtu"] = 0;
        }
        if (!("ipv4" in $$source)) {
            this["ipv4"] = "";
        }
        if (!("ipv6" in $$source)) {
            this["ipv6"] = "";
        }
        if (!("blockQuic" in $$source)) {
            this["blockQuic"] = false;
        }
        if (!("socksUdp" in $$source)) {
            this["socksUdp"] = "";
        }
        if (!("socksMark" in $$source)) {
            this["socksMark"] = 0;
        }
        if (!("routeTable" in $$source)) {
            this["routeTable"] = 0;
        }
        if (!("logLevel" in $$source)) {
            this["logLevel"] = "";
        }
        if (!("mapDnsEnabled" in $$source)) {
            this["mapDnsEnabled"] = false;
        }
        if (!("mapDnsAddress" in $$source)) {
            this["mapDnsAddress"] = "";
        }
        if (!("mapDnsPort" in $$source)) {
            this["mapDnsPort"] = 0;
        }
        if (!("mapDnsNetwork" in $$source)) {
            this["mapDnsNetwork"] = "";
        }
        if (!("mapDnsNetmask" in $$source)) {
            this["mapDnsNetmask"] = "";
        }
        if (!("taskStackSize" in $$source)) {
            this["taskStackSize"] = 0;
        }
        if (!("tcpBufferSize" in $$source)) {
            this["tcpBufferSize"] = 0;
        }
        if (!("maxSession" in $$source)) {
            this["maxSession"] = 0;
        }
        if (!("connectTimeout" in $$source)) {
            this["connectTimeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): TunSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunSettings($$parsedSource as Partial<TunSettings>);
    }
}

export class UISettings {
    "language": string;
    "theme": string;
    "launchAtLogin": boolean;

    /** Creates a new UISettings instance. */
    constructor($$source: Partial<UISettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("launchAtLogin" in $$source)) {
            this["launchAtLogin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UISettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UISettings($$parsedSource as Partial<UISettings>);
    }
}

export class UsageDay {
    "date": string;
    "tx": number;
    "rx": number;
    "directTx": number;
    "directRx": number;
    "proxyTx": number;
    "proxyRx": number;

    /** Creates a new UsageDay instance. */
    constructor($$source: Partial<UsageDay> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("tx" in $$source)) {
            this["tx"] = 0;
        }
        if (!("rx" in $$source)) {
            this["rx"] = 0;
        }
        if (!("directTx" in $$source)) {
            this["directTx"] = 0;
        }
        if (!("directRx" in $$source)) {
            this["directRx"] = 0;
        }
        if (!("proxyTx" in $$source)) {
            this["proxyTx"] = 0;
        }
        if (!("proxyRx" in $$source)) {
            this["proxyRx"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageDay instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageDay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageDay($$parsedSource as Partial<UsageDay>);
    }
}

// Private type creation functions
const $$createType0 = NodeConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RoutingSettings.createFrom;
const $$createType3 = TunSettings.createFrom;
const $$createType4 = CoreSettings.createFrom;
const $$createType5 = ReverseClientSettings.createFrom;
const $$createType6 = ReverseForwarderSettings.createFrom;
const $$createType7 = PortForwardRule.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = UISettings.createFrom;
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = HTTPMaskSettings.createFrom;
const $$createType12 = ReverseRoute.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = TrafficState.createFrom;
const $$createType15 = LatencyResult.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ActiveConnection.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = LogEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = BandwidthSample.createFrom;
const $$createType22 = $Create.Array($$createType21);
