import * as App from '../bindings/github.com/SUDOKU-ASCII/sudoku-desktop/app'
import type {
  ActiveConnection,
  AppConfig,
  IPDetectResult,
  LatencyResult,
  LogEntry,
  NodeConfig,
  RuntimeState,
  StartRequest,
  UsageDay,
} from './types'

export const backendApi = {
  getConfig: () => App.GetConfig() as Promise<AppConfig>,
  saveConfig: (cfg: AppConfig) => App.SaveConfig(cfg) as Promise<void>,
  getState: () => App.GetState() as Promise<RuntimeState>,
  startProxy: (req: StartRequest) => App.StartProxy(req) as Promise<void>,
  stopProxy: () => App.StopProxy() as Promise<void>,
  restartProxy: (req: StartRequest) => App.RestartProxy(req) as Promise<void>,
  tunHasPrivileges: () => App.TunHasPrivileges() as Promise<boolean>,
  tunAcquirePrivileges: (password: string) => App.TunAcquirePrivileges(password) as Promise<void>,
  tunDropPrivileges: () => App.TunDropPrivileges() as Promise<void>,
  upsertNode: (node: NodeConfig) => App.UpsertNode(node) as Promise<NodeConfig>,
  deleteNode: (id: string) => App.DeleteNode(id) as Promise<void>,
  switchNode: (id: string) => App.SwitchNode(id) as Promise<void>,
  exportShortLink: (id: string) => App.ExportShortLink(id) as Promise<string>,
  importShortLink: (name: string, link: string) => App.ImportShortLink(name, link) as Promise<NodeConfig>,
  probeNode: (id: string) => App.ProbeNode(id) as Promise<LatencyResult>,
  probeAllNodes: () => App.ProbeAllNodes() as Promise<LatencyResult[]>,
  autoSelectLowestLatency: () => App.AutoSelectLowestLatency() as Promise<LatencyResult>,
  sortNodesByName: () => App.SortNodesByName() as Promise<void>,
  sortNodesByLatency: () => App.SortNodesByLatency() as Promise<void>,
  detectIPDirect: () => App.DetectIPDirect() as Promise<IPDetectResult>,
  detectIPProxy: () => App.DetectIPProxy() as Promise<IPDetectResult>,
  startReverseForwarder: () => App.StartReverseForwarder() as Promise<void>,
  stopReverseForwarder: () => App.StopReverseForwarder() as Promise<void>,
  getLogs: (level: string, limit: number) => App.GetLogs(level, limit) as Promise<LogEntry[]>,
  getConnections: () => App.GetConnections() as Promise<ActiveConnection[]>,
  closeConnection: (id: string) => App.CloseConnection(id) as Promise<void>,
  closeAllConnections: () => App.CloseAllConnections() as Promise<void>,
  getUsageHistory: (limit: number) => App.GetUsageHistory(limit) as Promise<UsageDay[]>,
  validateYAML: (content: string) => App.ValidateYAML(content) as Promise<void>,
}
