// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSelectLowestLatency() {
  return window['go']['main']['App']['AutoSelectLowestLatency']();
}

export function BuildInfo() {
  return window['go']['main']['App']['BuildInfo']();
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DetectIPDirect() {
  return window['go']['main']['App']['DetectIPDirect']();
}

export function DetectIPProxy() {
  return window['go']['main']['App']['DetectIPProxy']();
}

export function EnsureCoreBinaries() {
  return window['go']['main']['App']['EnsureCoreBinaries']();
}

export function ExportShortLink(arg1) {
  return window['go']['main']['App']['ExportShortLink'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetUsageHistory(arg1) {
  return window['go']['main']['App']['GetUsageHistory'](arg1);
}

export function ImportShortLink(arg1, arg2) {
  return window['go']['main']['App']['ImportShortLink'](arg1, arg2);
}

export function OpenConfigPath() {
  return window['go']['main']['App']['OpenConfigPath']();
}

export function OpenRuntimeDir() {
  return window['go']['main']['App']['OpenRuntimeDir']();
}

export function ProbeAllNodes() {
  return window['go']['main']['App']['ProbeAllNodes']();
}

export function ProbeNode(arg1) {
  return window['go']['main']['App']['ProbeNode'](arg1);
}

export function RestartProxy(arg1) {
  return window['go']['main']['App']['RestartProxy'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetActiveNode(arg1) {
  return window['go']['main']['App']['SetActiveNode'](arg1);
}

export function SortNodesByLatency() {
  return window['go']['main']['App']['SortNodesByLatency']();
}

export function SortNodesByName() {
  return window['go']['main']['App']['SortNodesByName']();
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StartReverseForwarder() {
  return window['go']['main']['App']['StartReverseForwarder']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopReverseForwarder() {
  return window['go']['main']['App']['StopReverseForwarder']();
}

export function SwitchNode(arg1) {
  return window['go']['main']['App']['SwitchNode'](arg1);
}

export function UpsertNode(arg1) {
  return window['go']['main']['App']['UpsertNode'](arg1);
}

export function ValidateYAML(arg1) {
  return window['go']['main']['App']['ValidateYAML'](arg1);
}
