// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AutoSelectLowestLatency():Promise<core.LatencyResult>;

export function BuildInfo():Promise<Record<string, string>>;

export function DeleteNode(arg1:string):Promise<void>;

export function DetectIPDirect():Promise<core.IPDetectResult>;

export function DetectIPProxy():Promise<core.IPDetectResult>;

export function EnsureCoreBinaries():Promise<void>;

export function ExportShortLink(arg1:string):Promise<string>;

export function GetConfig():Promise<core.AppConfig>;

export function GetConnections():Promise<Array<core.ActiveConnection>>;

export function GetLogs(arg1:string,arg2:number):Promise<Array<core.LogEntry>>;

export function GetState():Promise<core.RuntimeState>;

export function GetUsageHistory(arg1:number):Promise<Array<core.UsageDay>>;

export function ImportShortLink(arg1:string,arg2:string):Promise<core.NodeConfig>;

export function OpenConfigPath():Promise<string>;

export function OpenRuntimeDir():Promise<string>;

export function ProbeAllNodes():Promise<Array<core.LatencyResult>>;

export function ProbeNode(arg1:string):Promise<core.LatencyResult>;

export function RestartProxy(arg1:core.StartRequest):Promise<void>;

export function SaveConfig(arg1:core.AppConfig):Promise<void>;

export function SetActiveNode(arg1:string):Promise<void>;

export function SortNodesByLatency():Promise<void>;

export function SortNodesByName():Promise<void>;

export function StartProxy(arg1:core.StartRequest):Promise<void>;

export function StartReverseForwarder():Promise<void>;

export function StopProxy():Promise<void>;

export function StopReverseForwarder():Promise<void>;

export function SwitchNode(arg1:string):Promise<void>;

export function UpsertNode(arg1:core.NodeConfig):Promise<core.NodeConfig>;
